name: Cleanup Old Releases
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    tags:
      - "v*.*.*"  # Runs when a new tag (release) is pushed

jobs:
  cleanup-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1  # Number of latest releases to keep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Requires repo permissions